import type { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";
import { AnimationContainer, MaxWidthWrapper } from "@/components";
import QuoteCalculator from "@/components/quote/quote-calculator";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { CheckListItem } from "@/components/ui/check-list";
import { PrimaryButton } from "@/components/ui/primary-button";
import { Section, SectionHeader } from "@/components/ui/section";
import { StarsBackground } from "@/components/ui/stars-background";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { AREA, BRAND } from "@/lib/seo/keywords";
import {
  pricingCtas,
  pricingExamples,
  pricingNotes,
  pricingTables,
} from "@/lib/pricing/price-examples";
import { generateMetadata } from "@/utils";

const TITLE = `Cleaning Prices in ${AREA} | ${BRAND}`;
const DESCRIPTION =
  "Cleaning prices in Plymouth are calculated instantly with our booking calculator. Pricing depends on property size, service level, frequency, and add-ons.";
const CANONICAL = "/cleaning-prices-plymouth";

const BASE_METADATA = generateMetadata({
  title: TITLE,
  description: DESCRIPTION,
});

export const metadata: Metadata = {
  ...BASE_METADATA,
  alternates: {
    canonical: CANONICAL,
  },
  openGraph: {
    ...(BASE_METADATA.openGraph ?? {}),
    title: TITLE,
    description: DESCRIPTION,
    url: CANONICAL,
  },
  twitter: {
    ...(BASE_METADATA.twitter ?? {}),
    title: TITLE,
    description: DESCRIPTION,
  },
};

const LOCAL_BUSINESS_JSON_LD = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  name: BRAND,
  url: "https://sparkandmend.co.uk",
  areaServed: AREA,
};

const heroSurface =
  "relative overflow-hidden rounded-[36px] border border-border/50 bg-[radial-gradient(120%_120%_at_80%_0%,hsl(var(--background))_0%,hsl(var(--subtle))_45%,hsl(var(--background))_100%)] px-6 pt-10 pb-12 md:px-12 md:pt-12 md:pb-14 shadow-[0_45px_100px_-70px_hsl(var(--primary)/0.45)]";
const sectionBase =
  "relative overflow-hidden rounded-[32px] border border-border/50 px-6 py-10 md:px-10 md:py-12 shadow-[0_30px_80px_-60px_hsl(var(--primary)/0.35)]";
const surfacePrimary =
  "bg-[linear-gradient(135deg,hsl(var(--primary)/0.08),hsl(var(--background))_70%)]";
const surfaceSoft =
  "bg-[linear-gradient(135deg,hsl(var(--subtle))_0%,hsl(var(--background))_75%)]";
const surfaceNeutral =
  "bg-[linear-gradient(135deg,hsl(var(--card))_0%,hsl(var(--background))_85%)]";
const surfaceMuted =
  "bg-[linear-gradient(135deg,hsl(var(--muted))_0%,hsl(var(--background))_85%)]";

const pricingTablesList = [
  pricingTables.regular,
  pricingTables.deep,
  pricingTables.endOfTenancy,
  pricingTables.commercial,
];

const costFactors = [
  "Property size and number of rooms",
  "Bathrooms and high-use areas",
  "Current condition and build-up, reflected in service level",
  "Visit frequency for regular cleans",
  "Add-ons like oven, fridge, or interior windows",
  "Custom requests shared in the quote notes",
];

const CleaningPricesPlymouthPage = () => {
  return (
    <MaxWidthWrapper className="pt-16 pb-20">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(LOCAL_BUSINESS_JSON_LD),
        }}
      />
      <Section className={heroSurface}>
        <StarsBackground
          className="absolute inset-0 opacity-60"
          starColor="#09484F"
          pointerEvents={false}
        />
        <AnimationContainer delay={0.1} className="relative z-10">
          <div className="grid gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:items-center">
            <div className="text-center lg:text-left">
              <SectionHeader
                eyebrow="Plymouth"
                title={`Cleaning Prices in ${AREA}`}
                description="Get transparent pricing generated by our booking calculator. Prices update with your service level, home size, and schedule."
                align="left"
              />
              <p className="mt-4 text-sm text-muted-foreground">
                Serving Plymouth only. Use the calculator for exact pricing and
                availability.
              </p>
              <div className="mt-6 flex flex-wrap gap-3 justify-center lg:justify-start">
                <PrimaryButton asChild>
                  <Link href="/get-a-quote">Arrange a FREE clean</Link>
                </PrimaryButton>
                <Button variant="outline" asChild>
                  <Link href="#price-ranges">View price ranges</Link>
                </Button>
              </div>
            </div>
            <div className="rounded-3xl border border-border/60 bg-card/80 p-6 text-left shadow-[0_30px_70px_-55px_hsl(var(--primary)/0.45)]">
              <p className="text-sm uppercase tracking-[0.2em] text-muted-foreground">
                Quick booking links
              </p>
              <div className="mt-4 flex flex-wrap gap-2">
                {pricingCtas.map((cta) => (
                  <Button key={cta.href} variant="outline" size="sm" asChild>
                    <Link href={cta.href}>{cta.label}</Link>
                  </Button>
                ))}
              </div>
            </div>
          </div>
        </AnimationContainer>
      </Section>

      <Section id="price-ranges" className={`${sectionBase} ${surfacePrimary}`}>
        <AnimationContainer delay={0.2}>
          <SectionHeader
            eyebrow="Ranges"
            title="Price ranges by service and property size"
            description="These ranges are generated from the same calculator used in the booking form. They assume no add-ons and typical layouts."
          />
          <div className="mt-8 grid gap-6">
            {pricingTablesList.map((table) => (
              <Card key={table.title} className="border-none bg-card/85">
                <CardHeader>
                  <CardTitle className="text-lg font-semibold text-foreground">
                    {table.title}
                  </CardTitle>
                  <CardDescription>{table.priceLabel}</CardDescription>
                </CardHeader>
                <CardContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Property size</TableHead>
                        <TableHead>Estimated price</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {table.rows.map((row) => (
                        <TableRow key={`${table.title}-${row.label}`}>
                          <TableCell className="font-medium text-foreground">
                            {row.label}
                          </TableCell>
                          <TableCell>{row.estimate}</TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
            ))}
          </div>
          <ul className="mt-6 space-y-2 text-sm text-muted-foreground">
            {pricingNotes.map((note) => (
              <CheckListItem key={note}>{note}</CheckListItem>
            ))}
          </ul>
        </AnimationContainer>
      </Section>

      <Section className={`${sectionBase} ${surfaceNeutral}`}>
        <AnimationContainer delay={0.25}>
          <SectionHeader
            eyebrow="Examples"
            title="Example prices generated from the calculator"
            description="Real examples based on common property sizes and schedules."
          />
          <div className="mt-8 grid gap-6 md:grid-cols-2">
            {pricingExamples.map((example) => (
              <Card key={example.title} className="border-none bg-card/85">
                <CardHeader className="space-y-2">
                  <CardTitle className="text-lg font-semibold text-foreground">
                    {example.title}
                  </CardTitle>
                  <CardDescription>{example.detail}</CardDescription>
                </CardHeader>
                <CardContent className="text-sm text-muted-foreground">
                  <p className="text-2xl font-semibold text-foreground">
                    {example.price}
                  </p>
                  <p className="mt-1 text-xs uppercase tracking-[0.2em] text-muted-foreground">
                    {example.priceLabel}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </AnimationContainer>
      </Section>

      <Section className={`${sectionBase} ${surfaceSoft}`}>
        <AnimationContainer delay={0.3}>
          <SectionHeader
            eyebrow="What affects cost"
            title="What drives the price of a clean"
            description="We keep pricing transparent and adjust it to your space and schedule."
            align="left"
          />
          <ul className="mt-6 space-y-2 text-muted-foreground">
            {costFactors.map((item) => (
              <CheckListItem key={item}>{item}</CheckListItem>
            ))}
          </ul>
        </AnimationContainer>
      </Section>

      <Section className={`${sectionBase} ${surfaceMuted}`}>
        <AnimationContainer delay={0.35}>
          <SectionHeader
            eyebrow="Instant pricing"
            title="Get an exact price in minutes"
            description="Pick your service, property details, and schedule to see your exact price in about 60 seconds."
            align="left"
          />
          <div className="mt-8">
            <Suspense
              fallback={
                <div className="rounded-3xl border border-border/60 bg-card/70 p-6 text-sm text-muted-foreground">
                  Loading the booking form...
                </div>
              }
            >
              <QuoteCalculator />
            </Suspense>
          </div>
        </AnimationContainer>
      </Section>

      <Section>
        <div className="flex flex-col items-center gap-4 rounded-3xl border border-border/70 bg-card/90 px-6 py-10 text-center shadow-[0_30px_70px_-50px_hsl(var(--primary)/0.5)] md:px-12 md:py-12">
          <h2 className="text-3xl md:text-4xl font-semibold font-heading text-foreground">
            Ready for your exact quote?
          </h2>
          <p className="text-base md:text-lg text-muted-foreground">
            Use the calculator to confirm a clear price and book your
            Plymouth clean.
          </p>
          <div className="mt-6 flex flex-wrap justify-center gap-3">
            <PrimaryButton asChild>
              <Link href="/get-a-quote">Arrange a FREE clean</Link>
            </PrimaryButton>
            {pricingCtas.map((cta) => (
              <Button key={cta.href} variant="outline" asChild>
                <Link href={cta.href}>{cta.label}</Link>
              </Button>
            ))}
          </div>
        </div>
      </Section>
    </MaxWidthWrapper>
  );
};

export default CleaningPricesPlymouthPage;
